# Generated by Django 5.0.1 on 2026-02-02 19:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total credits accumulated from transaction cuts', max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bank',
                'verbose_name_plural': 'bank',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=150)),
                ('credits', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='User credit balance', max_digits=10)),
                ('is_online', models.BooleanField(default=False, help_text='Whether user is currently online')),
                ('last_support_request', models.DateTimeField(blank=True, help_text='Last time user requested support credits', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='LearningRequestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_to_learn', models.CharField(help_text='Topic the user wants to learn', max_length=255)),
                ('topic_to_teach', models.CharField(blank=True, default='', help_text='Topic the user can teach in exchange (optional)', max_length=255)),
                ('ok_with_just_learning', models.BooleanField(default=False, help_text='User is okay with just learning (paying credits)')),
                ('bounty_enabled', models.BooleanField(default=False, help_text='User is willing to pay extra credits as bounty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this learning request has been fulfilled')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'learning request post',
                'verbose_name_plural': 'learning request posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('learning_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.learningrequestpost')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='', help_text='Optional review comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.session')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for earned, negative for spent', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('TEACHING', 'Teaching Earned'), ('LEARNING', 'Learning Spent'), ('SIGNUP', 'Signup Bonus'), ('SUPPORT', 'Bank Support'), ('BANK_CUT', 'Bank Cut')], max_length=20)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='User balance after this transaction', max_digits=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='core.session')),
            ],
            options={
                'verbose_name': 'credit transaction',
                'verbose_name_plural': 'credit transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Calculated duration when timer stops')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='core.session')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_timers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session timer',
                'verbose_name_plural': 'session timers',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='learningrequestpost',
            index=models.Index(fields=['is_completed', '-created_at'], name='core_learni_is_comp_8fe285_idx'),
        ),
        migrations.AddIndex(
            model_name='learningrequestpost',
            index=models.Index(fields=['creator', 'is_completed'], name='core_learni_creator_931db5_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_active', '-start_time'], name='core_sessio_is_acti_46814e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee', '-created_at'], name='core_review_reviewe_56640a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('session', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['user', '-created_at'], name='core_credit_user_id_c97634_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='core_credit_transac_fa875c_idx'),
        ),
    ]
