# Generated by Django 6.0.1 on 2026-02-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.CharField(blank=True, help_text='User availability (e.g., "Mon-Fri 9am-5pm")', max_length=255, null=True),
        ),
    ]
