# Generated by Django 6.0.1 on 2026-02-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time user was seen active', null=True),
        ),
    ]
