# Generated by Django 6.0.1 on 2026-03-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_session_code_data_session_last_sync_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user1_last_room_presence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='user2_last_room_presence',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
