# Generated by Django 6.0.1 on 2026-03-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_session_user1_last_room_presence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_date',
            field=models.DateField(blank=True, help_text='Last date the user logged in for streak tracking', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_streak',
            field=models.IntegerField(default=0, help_text='Current consecutive login streak in days'),
        ),
    ]
