# Generated by Django 6.0.1 on 2026-03-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_session_learning_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='learning_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.learningrequestpost'),
        ),
    ]
