# Generated by Django 6.0.1 on 2026-03-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_session_learning_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sync_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='signal_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
